### ISSUE TITLE
time argument in seconds

### ISSUE THREAD

**Issue by michelalbonico** [S2-group/rosbag-extractor#10]
Optionally, pass time arguments in seconds instead of the precise date and time.

For example from second 1 to second 5.

**Comment by BerryC-VU** [comment]
The flag "-s" represents the input start time, "-e" represents the input end time

An example to check bagfile 'talker' from second 1 to second 5: 
            `python3 extractor.py -v=ros2 -s=1 -e=5 -f=bagfiles/ros2/talker -ft=db3`
