### ISSUE TITLE
no datetime parameter

### ISSUE THREAD

**Issue by michelalbonico** [S2-group/rosbag-extractor#11]
If no datetime parameter is passed, generate the graph of the whole bag.

**Comment by BerryC-VU** [comment]
Example commands:

1. Without **start time** parameter
`python3 extractor.py -v=ros2 -e=4 -f=bagfiles/ros2/talker -ft=db3` -> This command results in the computation graph from the start of the bagfile to the second 4 of the bagfile.
2. Without **end time** parameter
`python3 extractor.py -v=ros2 -s=2 -f=bagfiles/ros2/talker -ft=db3` -> This command results in the graph from the second 2 of the bagfile to the end of the bagfile.
3. No datetime parameter
`python3 extractor.py -v=ros2 -f=bagfiles/ros2/talker -ft=db3` -> This command results in the graph of the whole bag.
