### ISSUE TITLE
graphs in different folders

### ISSUE THREAD

**Issue by michelalbonico** [S2-group/rosbag-extractor#2]
Organize the generated graphs in a different folder than ros bag one.

**Comment by BerryC-VU** [comment]
- Output files are saved in a folder with the same name as the bagfile. 
- Each folder contains three files: **.pdf** (output graph), **.dot**(compatible with RQT tool), and a **source file**. 
- The folder can be found in the `graphs` directory with subfolders `/ros1` and `/ros2`.
