### ISSUE TITLE
support new rosbag formats

### ISSUE THREAD

**Issue by michelalbonico** [S2-group/rosbag-extractor#3]
There are also some news related to the rosbag format: https://docs.ros.org/en/iron/Releases/Release-Iron-Irwini.html#rosbag2

**Comment by BerryC-VU** [comment]
Flag `-ft` is used to represent filetype when parsing the argument

- For ROS1: 
    - valid bag format is **bag**
    - `python3 extractor.py -v=ros1 -f=bagfiles/ros1/turtlesim -ft=bag`
- For ROS2:
    -  valid bag formats are **db3** and **mcap**
    - `python3 extractor.py -v=ros2 -f=bagfiles/ros2/talker -ft=db3`
    - `python3 extractor.py -v=ros2 -f=bagfiles/ros2/mcap1 -ft=mcap`
