### ISSUE TITLE
add metrics

### ISSUE THREAD

**Issue by michelalbonico** [S2-group/rosbag-extractor#5]
nodes, topics, connection, services, etc.

**Comment by michelalbonico** [comment]
@BerryC-VU how can I validade this? Please, provide an example.

**Comment by BerryC-VU** [comment]
After extraction, the metric file(s) will be generated and can be found under the `metric` folder with `.json` extension

**Comment by michelalbonico** [comment]
@iivanoo please, check whether it fits your demand.

**Comment by iivanoo** [comment]
Looks good.
