### ISSUE TITLE
create the node provider

### ISSUE THREAD

**Issue by michelalbonico** [S2-group/rosbag-extractor#6]
“Node provider” function
Check the newest version of ROS(Iron Irwini)
What’s the difference in bagfiles compared to old versions?

Format, collected information, data type, etc.
‘Service introspection’ provides any information on services. Is the information recorded in the bag?
Extract the computation graph based on the input file
CSV/JSON input file
What should be included in the file?
nodes, timestamps about when the nodes are up or down, connection, frequency, messages
Check the file and information that rosdiscover results in.
Read the file and extract

**Comment by BerryC-VU** [comment]
The activation of this function is through parsing "-i=<path to file>". In this context, the flag ‘i’ represents the external input. The string ‘path to file’ indicates the path to the file containing the nodes’ information.

An example of extracting a computation graph with the node provider:
`python3 extractor.py -v=ros2 -f=bagfiles/ros2/talker -ft=db3 -i=path_to_file` -> This will result in a computation graph of the whole bag with the provided node information.

**Comment by michelalbonico** [comment]
@BerryC-VU please, provide a file that can be used to validate this.
