### ISSUE TITLE
support input from other tools

### ISSUE THREAD

**Issue by michelalbonico** [S2-group/rosbag-extractor#8]
The tool should allow inputs from other tools such as ROSDiscover. For example, we could accept the ROSDiscovery yaml file as a parameter and read tags from it.

"Extract the computation graph based on the input file
CSV/JSON input file
What should be included in the file?
nodes, timestamps about when the nodes are up or down, connection, frequency, messages
Check the file and information that rosdiscover results in.
Read the file and extract "

**Comment by BerryC-VU** [comment]
In order to include files from other tools, input must be converted into CSV file format and include the following columns:

- Name: Type String
- Publish: Type List 
- Subscribe: Type List
- Node-start: Type Float  (Optional)
- Node-end: Type Float (Optional)

**Comment by michelalbonico** [comment]
@iivanoo please, take a look at this to see whether it can be this way.
